
package com.playmovie.locadora.servicos;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ListagemFilmesService", targetNamespace = "http://servicos.locadora.playmovie.com/", wsdlLocation = "http://localhost:8080/filmes?wsdl")
public class ListagemFilmesService
    extends Service
{

    private final static URL LISTAGEMFILMESSERVICE_WSDL_LOCATION;
    private final static WebServiceException LISTAGEMFILMESSERVICE_EXCEPTION;
    private final static QName LISTAGEMFILMESSERVICE_QNAME = new QName("http://servicos.locadora.playmovie.com/", "ListagemFilmesService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/filmes?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LISTAGEMFILMESSERVICE_WSDL_LOCATION = url;
        LISTAGEMFILMESSERVICE_EXCEPTION = e;
    }

    public ListagemFilmesService() {
        super(__getWsdlLocation(), LISTAGEMFILMESSERVICE_QNAME);
    }

    public ListagemFilmesService(WebServiceFeature... features) {
        super(__getWsdlLocation(), LISTAGEMFILMESSERVICE_QNAME, features);
    }

    public ListagemFilmesService(URL wsdlLocation) {
        super(wsdlLocation, LISTAGEMFILMESSERVICE_QNAME);
    }

    public ListagemFilmesService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LISTAGEMFILMESSERVICE_QNAME, features);
    }

    public ListagemFilmesService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ListagemFilmesService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ListagemFilmes
     */
    @WebEndpoint(name = "ListagemFilmesPort")
    public ListagemFilmes getListagemFilmesPort() {
        return super.getPort(new QName("http://servicos.locadora.playmovie.com/", "ListagemFilmesPort"), ListagemFilmes.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ListagemFilmes
     */
    @WebEndpoint(name = "ListagemFilmesPort")
    public ListagemFilmes getListagemFilmesPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://servicos.locadora.playmovie.com/", "ListagemFilmesPort"), ListagemFilmes.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LISTAGEMFILMESSERVICE_EXCEPTION!= null) {
            throw LISTAGEMFILMESSERVICE_EXCEPTION;
        }
        return LISTAGEMFILMESSERVICE_WSDL_LOCATION;
    }

}
