
package com.playmovie.locadora.servicos;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ListagemFilmes", targetNamespace = "http://servicos.locadora.playmovie.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ListagemFilmes {


    /**
     * 
     * @return
     *     returns java.util.List<com.playmovie.locadora.servicos.Filme>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listarFilmes", targetNamespace = "http://servicos.locadora.playmovie.com/", className = "com.playmovie.locadora.servicos.ListarFilmes")
    @ResponseWrapper(localName = "listarFilmesResponse", targetNamespace = "http://servicos.locadora.playmovie.com/", className = "com.playmovie.locadora.servicos.ListarFilmesResponse")
    @Action(input = "http://servicos.locadora.playmovie.com/ListagemFilmes/listarFilmesRequest", output = "http://servicos.locadora.playmovie.com/ListagemFilmes/listarFilmesResponse")
    public List<Filme> listarFilmes();

}
